site_banner: '<div class="navbar-brand" /div>'

site_name: 'Leeson Consulting'

copyright: Copyright &copy; 2024 Leeson Consulting Ltd.

nav:
  - Haere mai: 'index.md'
  - Leeson:
    - 'leeson/index.md'
  - Open Source:
    - 'open_source/index.md'
  - Protocol Design:
    - 'protocol_design/index.md'
  - License: 'license.md'

theme:
  name: material
  custom_dir: overrides
  logo: assets/leeson_logo.svg
  favicon: assets/leeson_logo_192x192.png
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.footer
    - content.code.copy
    - content.code.select

plugins:
  - awesome-pages
  - blog:
      blog_dir: leeson
  - blog:
      blog_dir: open_source
  - blog:
      blog_dir: protocol_design
  - search

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

extra_css:
  - stylesheets/leeson.css

